services:
  - type: web
    name: fastapi-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    repo: https://github.com/your/repo
    branch: main

  - type: web
    name: streamlit-frontend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port 8501 --server.address 0.0.0.0"
    repo: https://github.com/your/repo
    branch: main
